- app/models/user.rb
- app/views/pages/home.html.erb
- config/routes.rb
Added a validation for email and routes for prompts
> added a validation for email and routes for prompts

- app/models/code_review.rb
- app/views/pages/home.html.erb
- config/routes.rb
route code_reviews, has one attached file, add button get started
> route code_reviews, has one attached file, add button get started

- app/controllers/code_reviews_controller.rb
- app/controllers/prompts_controller.rb
- app/models/prompt.rb
- app/views/prompts/_form.html.erb
- app/views/prompts/new.html.erb
> created simple form and def to both controllers

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
Added a navbar with spacing, color change and underline animation on hover.
> added a navbar

- app/assets/config/manifest.js
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/prompts/new.scss
- app/views/layouts/application.html.erb
- app/views/prompts/new.html.erb
- app/views/shared/_footer.html.erb
Added a footer, made it sticky except for the new.html.erb where i made it relative.
> added a footer

- Gemfile
- Gemfile.lock
- app/controllers/code_reviews_controller.rb
- app/services/openai_service.rb
- config/initializers/openai.rb
Instal gem,
add the token from chatgpt,
created files and folders.
> open ia gem and files

- app/assets/stylesheets/components/_footer.scss
Shorten the footer and fixed the spacing on the new prompts page
> shorten the footer and fic+xed the spacing on the new prompts page

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
Added logo-container div for the logo in the navbar.  Added margin-left for the container and margin-right for the links.
> added container for logo and changed the spacing

- app/assets/config/manifest.js
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/prompts/show.scss
- app/views/prompts/show.html.erb
Added color variables and fixed footer for the show page
> added color variables and fixed footer for the show page

- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/prompts/show.scss
Imported fonts and changed the font for the prompt in the show page
> imported fonts and changed the font for the prompt in the show page

- app/views/layouts/application.html.erb
- app/views/prompts/show.html.erb
- package.json
- yarn.lock
Now the code from the user answer is running
> added input for code

- Gemfile.lock
- app/views/prompts/show.html.erb
Added all the languages for the code input
> added all the languages for the code input

- app/models/prompt.rb
- app/services/challenge_prompt_service.rb
- package.json
- yarn.lock
now the prompt is working much better and we are having better answers from chatgpt
> nice prompt for chatgpt

- db/migrate/20230608094427_add_photo_to_users.rb
- db/schema.rb
Added a photo collumn to a users table
> added a photo collumn to a users table

- app/views/devise/confirmations/new.html.erb
- app/views/devise/registrations/new.html.erb
- db/schema.rb
> photo on the form

- app/views/layouts/application.html.erb
> removed footer

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
Next to the picture we have the name
> name on the navbar

- app/javascript/controllers/index.js
- app/views/layouts/application.html.erb
- app/views/prompts/show.html.erb
Now the code mirror looks like it's working fully
> working code mirror

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/prompts/show.scss
- app/views/prompts/show.html.erb
> frontend for challenge received

- app/assets/config/manifest.js
- app/assets/stylesheets/registrations/new.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
> sign up done

- app/assets/stylesheets/prompts/show.scss
- app/views/code_reviews/show.html.erb
- app/views/prompts/show.html.erb
> button is with border radius

- app/assets/stylesheets/code_reviews/index.scss
- app/assets/stylesheets/registrations/new.scss
- app/assets/stylesheets/users/new.scss
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/prompts/show.html.erb
> form login done

- app/assets/stylesheets/pages/_home.scss
changed hover and active bg color for buttons
> changed hover and active bg color for buttons

- app/assets/stylesheets/prompts/index.scss
- app/views/prompts/show.html.erb
Clipboard works but the div created a big space between the button and the content. I dont know how to fix it, Elvis probably knows.
> clipbpard is almost there
